name: Pedido de Participação no Open Source Friday Brasil
description: Preencha este formulário para solicitar participação no Open Source Friday Brasil
title: Open Source Friday - [NOME DO PROJETO] - [DD-MM-YYYY]

body:

type: markdown
attributes:
value: |
## Formulário de Convite para Open Source Friday
#### ✨ Por favor, preencha as informações abaixo para participar do Open Source Friday. A live acontece semanalmente às 13h BRT no canal da Twitch do GitHub. ✨

type: input
id: name
attributes:
label: Nome
description: Seu nome
placeholder: "Kedasha Kerr"

type: input
id: github_handle
attributes:
label: Usuário no GitHub
description: Seu usuário no GitHub
placeholder: "@LadyKerr"

type: textarea
id: about_you
attributes:
label: Conte-nos sobre você
description: Compartilhe um pouco sobre você e sua trajetória
placeholder: "Sou uma pessoa desenvolvedora que..."

type: input
id: project_name_1
attributes:
label: Nome do Projeto
description: Nome do projeto que você gostaria de apresentar e conversar sobre
placeholder: "Projeto Incrível"

type: input
id: project_repo_1
attributes:
label: Link do Repositório
description: O repositório do seu projeto no GitHub
placeholder: "github.com/repo-url"

type: checkboxes
id: stream_date
attributes:
label: Data da Live
description: Você já agendou uma data para sua live?
options:
- label: "Sim"
- label: "Ainda não"

type: input
id: dates_1
attributes:
label: Data
description: Qual data você agendou para a live do Open Source Friday Brasil?
placeholder: MM-DD-YYYY

type: input
id: social_twitter
attributes:
label: URL do Twitter
description: Seu perfil no Twitter
placeholder: "@itsthatladydev"

type: input
id: social_linkedin
attributes:
label: URL do LinkedIn
description: Seu perfil no LinkedIn
placeholder: "linkedin.com/in/seu-perfil"

type: textarea
id: more_info
attributes:
label: Informações Adicionais
description: Compartilhe qualquer outro detalhe que gostaria que soubéssemos sobre seu projeto
placeholder: "Gostaria de falar sobre..."
