name: Remind Hosts

on:
  issues:
    types: [labeled]

jobs:
  remind-hosts:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.event.label.name == 'scheduled'
    steps:
      - name: Comment on issue
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueComment = {
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: `Hi @pachicodes,\n\nThis stream has been scheduled. Please complete the following tasks:\n\n- [ ] Create social card\n- [ ] Create meetup link\n- [ ] Create and schedule social posts.`
            };
            await github.rest.issues.createComment(issueComment);
